### ISSUE TITLE
link broken for "Sign the royalty-free patent agreement required for TC39"

### ISSUE THREAD

**Issue by kumavis** [tc39/how-we-work#107]
this link redirects to this index page

https://github.com/tc39/how-we-work/blob/e01a22802db53803ec1be3ddb982e5c5ff3e9f02/join-tc39.md?plain=1#L9
```
< HTTP/2 301 
< location: https://www.ecma-international.org/policies/by-ipr/
```

**Comment by littledan** [comment]
Thanks for reporting this! Fix proposed.
