### ISSUE TITLE
Guiding principles

### ISSUE THREAD

**Issue by rkirsling** [tc39/how-we-work#29]
It seems it would be helpful to have a document of "guiding principles" for newcomers to keep in mind when making a proposal or prioritizing concerns that arise when evaluating proposals. (Perhaps this would also serve to address some ES Discuss noise, as @waldemarhorwat and @ljharb were relating.)

My understanding is that such principles may not currently exist in an official sense, but even a simple list of the things "in the ether" among the committee would be wonderful to have.

Whether this should exist as its own document or as a preface to, e.g., #1 is an open question.

**Comment by ctcpip** [comment]
it seems like this is covered via:

https://github.com/tc39/faq
https://github.com/tc39/how-we-work/pull/136
https://github.com/tc39/how-we-work/blob/main/terminology.md

if not, please reopen
