### ISSUE TITLE
Document TC39 glossary/technical goals

### ISSUE THREAD

**Issue by littledan** [tc39/how-we-work#3]
We have a lot of technical jargon and general design goals that we throw around in TC39, which would be good to have documented for proposal champions and other TC39 participants. @samuelgoto has identified this problem and is working on documentation for the issue.

Note, we've created [a repository](https://github.com/tc39/rationale) for this sort of purpose; not sure if it will be useful for this particular effort.

**Comment by ctcpip** [comment]
it seems like this is covered via:

https://github.com/tc39/how-we-work/blob/main/terminology.md
https://github.com/tc39/faq

if not, please reopen
