### ISSUE TITLE
Repeated abuse of power of moderation to proposal issues @tabatkins

### ISSUE THREAD

**Issue by stken2050** [tc39/how-we-work#97]
I'm afraid that this is the second report for the repeated abuse of power of moderation to proposal issues.

The previous report is
https://github.com/tc39/how-we-work/issues/95 by @stken2050
https://github.com/tc39/how-we-work/issues/96 by @kiprasmel 

@tabatkins is a champion of the current proposal and also a moderator of https://github.com/tc39/proposal-pipeline-operator/

I often observe he shuts down the discussion even middle of the debate once he feel it's against his own interest of the proposal.

What I report here is my own issue:
**Does the current proposal override the Grouping operator ( ) with Hack |> ?**
https://github.com/tc39/proposal-pipeline-operator/issues/229

Surely this has a significant impact to JavaScript as a whole and should be investigate thoroughly taking time, however he had shut this down making **invalid** in very short period of the time (**4 hours**).

![image](https://user-images.githubusercontent.com/1316994/134633557-8d07c914-5d1a-4769-b602-e9c217e9e16a.png)

After the shutdown by him, the discussion or investigation continued in another issue:
**Inconsistency of Type of the operator** 
https://github.com/tc39/proposal-pipeline-operator/issues/227

However, @tabatkins appeared and commented:

https://github.com/tc39/proposal-pipeline-operator/issues/227#issuecomment-926393643

>My closing of your previous thread is not an invitation to move the topic into another thread, @stken2050. I have marked this comment as off-topic; additional attempts to derail threads will be summarily deleted, and further CoC enforcement action may be pursued if you can't contribute productively.

This is pretty unreasonable threatening since I and other 2 or 3 members simply discussing the topic - **Does the current proposal override the Grouping operator ( ) with Hack |> ?**

**Here's my last comment, please investigate, I have discussed pure-math structure:**

https://github.com/tc39/proposal-pipeline-operator/issues/227#issuecomment-926371664

Then hiding around many comments at the same time

![image](https://user-images.githubusercontent.com/1316994/134633696-5dab5114-bc08-41a7-99a8-7ea43ffec37e.png)

![image](https://user-images.githubusercontent.com/1316994/134637388-4ec5fe72-c9dc-4716-91ee-cad428d656ed.png)

I firmly believe he is against code of conduct of the moderator and abuses his power shutting down the significant discussion is against the interest of community.

We feel @tabatkins  is so impulsive, and the transparency and healthy environment to productive discussion has been lost.

**Comment by kiprasmel** [comment]
they might ban you for this, just like they did with me:) stay strong

**Comment by davethegr8** [comment]
@stken2050 As we previously noted in #95, this is a meta repository for describing how TC39 works. It's not an escalation site for specific proposals, nor is it part of the Code of Conduct reporting process, so I'm closing this issue now.

There's plenty of time for constructive conversation and I encourage you to continue respectfully in other venues, e.g. [Matrix](https://github.com/tc39/how-we-work/blob/master/matrix-guide.md). 

If you believe there has been a Code of Conduct violation, the contact points and reporting guidelines are listed here: https://tc39.es/code-of-conduct/
